version: "3.7"
services:
  gocd-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./gocd-artifacts:/gocd-artifacts

  gocd-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      AGENT_AUTO_REGISTER_KEY: "cafecafe-4aab-4056-b325-9fbe25b9a734"
      GO_SERVER_URL: https://gocd-server:8154/go
